services:
  # The Node.js Server
  server:
    build: ./server
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    restart: unless-stopped

  # The Python Prediction Service
  prediction-service:
    build: ./finance-prediction-service
    ports:
      - "5001:5001"
    restart: unless-stopped

  # The React Client
  client:
    build: ./client
    ports:
      - "5173:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    restart: unless-stopped

  # The PostgreSQL Database Service
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres_data:
